baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    # status = "recruiting"
    # status = "signup" 
    status = "live"
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = "https://forms.gle/BZpCv6qNUzqzENMr8"
    menteeSignUp = "https://forms.gle/jESiwY7vVkmcgVh76"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1MEeI3-4P1akmZBYPN9lpD3nq0Oina4g09J2fe4V1NPM/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://forms.gle/3v5Xj16GBZjXWGe6A"
    submitPythonicLava = "https://forms.gle/qgY9QWtSXRoaf5ny7"
    current_startDate = 2021-10-10T14:15:59-06:00
    current_endDate   = 2021-12-04T14:15:59-06:00
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.renderer]
    unsafe= true
