baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    status = "recruiting"
    # status = "signup" 
    # status = "live"
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = "https://docs.google.com/forms/d/e/1FAIpQLSf2RlY8X_2R1mxsRTQSAbarf5vXf37lE7LXpyeQqpb2PxC-NQ/viewform?usp=sf_link"
    menteeSignUp = "https://docs.google.com/forms/d/e/1FAIpQLSe4cVntIe7ntBuxYRBoGuZZ4S9wbtvib0_9xQBifzBvG4qeFQ/viewform?usp=sf_link"
    recruitVideo = "https://youtu.be/L3TXTqKXAxY"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1jGEZZdHFjRzz-0btYQwd5MKphaB5llk79NSGg5BLhzA/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://forms.gle/pSuNHy4hcyBTg9oG7"
    submitPythonicLava = "https://forms.gle/6S73zw5jCEUgFUyx5"
    current_startDate = 2021-02-07
    current_endDate   = 2021-04-04
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"
