baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    # status = "closed" # When no recruitment is happening, and mailing list is available
    # status = "signup"     # When recruitment is happening
    status = "live"        # When courses are live
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = ""
    menteeSignUp = ""
    ignitePoints = ""
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = ""
    submitPythonicLava = ""
    submitScorch = "" 
    submitFlare = ""
    current_startDate = 2024-02-18T14:15:59-06:00
    current_endDate   = 2024-04-20T14:15:59-06:00
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.tableOfContents]
endLevel = 4 # End on H4's

[markup.goldmark.extensions]
footnote = true

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  author = "authors"
  tag = "tags"
  difficulty = "difficulty"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
