baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    status = "recruiting" # When no recruitment is happening, and mailing list is available
    #status = "signup"     # When recruitment is happening
    # status = "live"        # When courses are live
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = "https://forms.gle/QoKJ6i8QAMkXeJ1N7"
    menteeSignUp = "https://forms.gle/NmNLqfUAagydy9uj9"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1j1wdZsQyMoFeF6CSy4Hw8oes6vaf9auOVKWEhTp1rKk/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://docs.google.com/forms/d/e/1FAIpQLSc6_dmdkefRcO6HGkMBD-TFVLJtWDJmLy7-VJxHgK3BuuwzkA/viewform?usp=sharing"
    submitPythonicLava = "https://docs.google.com/forms/d/e/1FAIpQLSd2df9nYwyIgxXXj7_RQnFYooEcUucbeNXH3dTb6uDWZwXWVg/viewform?usp=sharing"
    submitScorch = "https://docs.google.com/forms/d/e/1FAIpQLSf1F_z_UR6lNSnDxw9zy5ddqMjUjHOzhHXsmIY9EOEY5_vBaQ/viewform?usp=share_link" 
    submitFlare = "https://docs.google.com/forms/d/e/1FAIpQLSeQh5PAsIaNDGg3DWdI4BxAFy7rx12_iu-lfxhtAeFB3gC34Q/viewform?usp=sharing"
    current_startDate = 2023-02-14T14:15:59-06:00
    current_endDate   = 2023-04-08T14:15:59-06:00
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.tableOfContents]
endLevel = 4 # End on H4's

[markup.goldmark.extensions]
footnote = true

[markup.goldmark.renderer]
    unsafe= true

[taxonomies]
  author = "authors"
  tag = "tags"
  difficulty = "difficulty"

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
