baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    # status = "recruiting"
    # status = "signup" 
    status = "live"
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = "https://docs.google.com/forms/d/e/1FAIpQLSfCw4Mj9tIjL8-12SQraDsLpdpjJfphnS-hTwNysVgop7sDTA/viewform"
    menteeSignUp = "https://docs.google.com/forms/d/e/1FAIpQLSfIZoyM7slznzXFfyvlsnSPrNvTG9tlRcuPRKMZORESMskKoQ/viewform"
    webMenteeSignUp = "https://forms.gle/GMxN7pmh8ZnyTBdv9"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1uCUz4_6qkJ6vtX8XUw-jqogvKdvsWLYxcLBDyhXPgsU/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://docs.google.com/forms/d/e/1FAIpQLSfy8VfD5mPXmtoKwtQcDvKDVz32aePRdtnvM8HS5PkhjFRvxQ/viewform?usp=sf_link"
    submitPythonicLava = "https://forms.gle/1BSY6H9CcuAPejUR8"
    current_startDate = 2022-10-10T14:15:59-06:00
    current_endDate   = 2022-12-03T14:15:59-06:00
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.renderer]
    unsafe= true
