baseURL = "https://schulichignite.com/"
languageCode = "en-us"
title = "Schulich Ignite"
summaryLength = 20
relativeURLs = true

[params]
    email = "info@schulichignite.com"
    # status = "recruiting"
    status = "signup" 
    # status = "live"
    emailListSignup = "https://forms.gle/ZJoDAbcTf1M3NBxYA"
    mentorSignUp = "https://forms.gle/BZpCv6qNUzqzENMr8"
    menteeSignUp = "https://forms.gle/jESiwY7vVkmcgVh76"
    ignitePoints = "https://docs.google.com/spreadsheets/d/1jGEZZdHFjRzz-0btYQwd5MKphaB5llk79NSGg5BLhzA/edit?usp=sharing"
    sparkDocs    = "https://spark.schulichignite.com/"
    submitBugBusters   = "https://forms.gle/pSuNHy4hcyBTg9oG7"
    submitPythonicLava = "https://forms.gle/6S73zw5jCEUgFUyx5"
    current_startDate = 2021-10-10
    current_endDate   = 2021-12-12
    [params.links]
        youtube = "https://www.youtube.com/channel/UC7tNvdbu952HOUl_4nK7iww"
        instagram = "https://www.instagram.com/schulichignite"
        facebook = "https://www.facebook.com/SchulichIgnite/"
        linkedin = "https://linkedin.com/company/schulich-ignite/"
        discord = "https://discord.gg/F3Qjqqj"
        tiktok  = "https://vm.tiktok.com/ZSHPbWU3/"

[markup.goldmark.renderer]
    unsafe= true
