backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
local_backend: true

publish_mode: editorial_workflow
media_folder: "static/img/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/blog" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "blog" # Used in the UI
  folder: "content/blog" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Subtitle", name: "subtitle", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime", hint: "Specifies when the article should be published"}
    - {label: "Modified Date", name: "modified_date", widget: "datetime", required: FALSE, hint: "Used if there is an update to the article", default: ""}
    - {label: "Featured Image", name: "image", widget: "image", required: FALSE}
    - label: Author
      name: author
      widget: object
      fields:
      - {label: "Author Name", name: "name", widget: "string"}
      - {label: "Author email", name: "email", widget: "string", required: FALSE}
      - {label: "Author linkedin", name: "linkedin", widget: "string", required: FALSE, hint: "Just the username (i.e. https://linkedin.com/in/kieran-wood would be entered here as kieran-wood)"}
      - {label: "Author Github", name: "github", widget: "string", required: FALSE, hint: "Just the username (i.e. https://github.com/descent098 would be entered here as descent098)"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}