name: Publish Site

on:
  push:
    branches:
      - master
  schedule:
    # Run every tuesday at 6:15pm for indigeSTEAM
    - cron:  '15 17 * * 1,3'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          compressOnly: true

      - name: Create New Pull Request If images were compressed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@master
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
  
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: schulichignite.com
