name: Publish Site

on:
  push:
    branches:
      - master
  schedule:
    # Run At 02:00 on Monday, Thursday, and Friday
    - cron:  '0 2 * * 1,4,5'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          compressOnly: true

      - name: Create New Pull Request If images were compressed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@main
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          body: ${{ steps.calibre.outputs.markdown }}
  
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          cname: schulichignite.com
